name: "ray job test"

on:
  workflow_dispatch:
  push:
    branches:
    - main

# env:
#   env_var: ${{ vars.action-ray-job-test }}

jobs:
# 1. get public address
# 2. white list public address
# 3. remove white list
  nvidia_smi_tset:
    environment: action-ray-job-test
    runs-on: ubuntu-latest
    steps:
    - name: get runner ip addresses
      id: ip
      uses: haythem/public-ip@v1.2
    - uses: aliyun/setup-aliyun-cli-action@v1
    - name: set up ak
      run: |
        aliyun configure set --mode AK --region ${{ vars.REGION_ID }} \
         --access-key-id ${{ secrets.ACCESS_KEY_ID }} --access-key-secret ${{ secrets.ACCESS_KEY_SECRET }}
    - name: print ip address
      run: |
        echo "${{ steps.ip.outputs.ipv4 }}/32"
    - name: add ip to adb whitelist
      run: |
        aliyun adb ModifyClusterAccessWhiteList --region ${{ vars.REGION_ID }} --DBClusterId '${{ vars.ADB_CLUSTER_ID }}' \
         --SecurityIps '${{ steps.ip.outputs.ipv4 }}/32' --ModifyMode Append --version 2021-12-01 --method POST --force
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        pip install -r ci/ray_utils/requirements.txt && echo "name: rayCluster01 address: ${{ secrets.RAY_ADDRESS }}" > ~/.cluster_config
    - name: submit nvidia-smi test to ray
      run: |
        python3 ci/ray_utils/submit_job.py --aggregate_jobs wrap_resources.py --test
    - run: git checkout HEAD
    - name: remove ip from adb whitelist
      run: |
        aliyun adb ModifyClusterAccessWhiteList --region ${{ vars.REGION_ID }} --DBClusterId '${{ vars.ADB_CLUSTER_ID }}' \
         --SecurityIps '${{ steps.ip.outputs.ipv4 }}/32' --ModifyMode Delete --version 2021-12-01 --method POST --force
