name: "ray job test"

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  nvidia_smi_test:
    environment: action-ray-job-test
    runs-on: ubuntu-latest
    steps:
    - name: get runner ip addresses
      id: ip
      uses: haythem/public-ip@v1.2
    - uses: aliyun/setup-aliyun-cli-action@v1
    - name: set up ak
      run: |
        aliyun configure set --mode AK --region ${{ vars.REGION_ID }} \
         --access-key-id ${{ secrets.ACCESS_KEY_ID }} --access-key-secret ${{ secrets.ACCESS_KEY_SECRET }}
    - name: add ip to adb whitelist
      uses: gacts/run-and-post-run@v1
      with:
        run: |
          aliyun adb ModifyClusterAccessWhiteList --region ${{ vars.REGION_ID }} --DBClusterId '${{ vars.ADB_CLUSTER_ID }}' \
          --SecurityIps '${{ steps.ip.outputs.ipv4 }}/32' --ModifyMode Append --version 2021-12-01 --method POST --force
        post: | # remove ip from adb whitelist
          aliyun adb ModifyClusterAccessWhiteList --region ${{ vars.REGION_ID }} --DBClusterId '${{ vars.ADB_CLUSTER_ID }}' \
          --SecurityIps '${{ steps.ip.outputs.ipv4 }}/32' --ModifyMode Delete --version 2021-12-01 --method POST --force
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        pip install -r ci/ray_utils/requirements.txt && echo "name: rayCluster01 address: ${{ secrets.RAY_ADDRESS }}" > ~/.cluster_config
    - name: submit nvidia-smi test to ray
      run: |
        python3 ci/ray_utils/submit_job.py --aggregate_jobs wrap_resources.py --test
    - name: submit reinforcement learning job to ray
      run: |
        python3 ci/ray_utils/submit_job.py --aggregate_jobs wrap_resources.py \
         --gpu_per_worker 2 3 4 --cpu_per_worker 32 32 32 --ram_gb_per_worker 128 128 128 \
         --sub_jobs /workspace/isaaclab/isaaclab.sh -p /workspace/isaaclab/scripts/reinforcement_learning/rl_games/train.py --task=Isaac-Cartpole-v0 --headless \
          + /workspace/isaaclab/isaaclab.sh -p /workspace/isaaclab/scripts/reinforcement_learning/rl_games/train.py --task=Isaac-Ant-v0 --headless \
           + /workspace/isaaclab/isaaclab.sh -p /workspace/isaaclab/scripts/reinforcement_learning/rl_games/train.py --task=Isaac-Ant-v0 --headless
